version: '3'

services:

  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - ../databases:/databases
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
    - "3306:3306"
    
  python:
    image: python:3.8
    volumes:
      - ../:/Mastering_DS_ML
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    links:
      - db
volumes:
  mysql-data:
  